
name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 0,12 * * *'  # At midnight & noon UTC

jobs:
  update-feeds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update feeds
        run: |
          echo $(pwd)
          mkdir -p  $env.FEED_FOLDER 
          curl -k -A Mozilla https://changelog.qgis.org/en/qgis/members/json/ -o ${{ env.FEED_FOLDER }}/members.json
          curl -k -A Mozilla https://changelog.qgis.org/en/qgis/past-members/json/?years_limit=2 -o ${{ env.FEED_FOLDER }}/qgispastmembers.json
