
name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 0,12 * * *'  # At midnight & noon UTC

jobs:
  update-feeds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update feeds
        run: |
          echo $(pwd)
          mkdir -p  $env.FEED_FOLDER 
          curl "https://api.flickr.com/services/feeds/groups_pool.gne?id=2244553@N22&lang=en-us&format=atom" -o ${{ env.FEED_FOLDER }}/qgisflickrmaps.atom
          curl "https://api.flickr.com/services/feeds/groups_pool.gne?id=2327386@N22&lang=en-us&format=atom" -o ${{ env.FEED_FOLDER }}/qgisflickrscreenshots.atom
          curl "https://plugins.qgis.org/planet/feed/atom/" -o ${{ env.FEED_FOLDER }}/qgisplanet.atom
          cp source/feeds/qugsnews.atom ${{ env.FEED_FOLDER }}/qugsnews.atom
          curl -k -A Mozilla https://changelog.qgis.org/en/qgis/members/json/ -o ${{ env.FEED_FOLDER }}/members.json
          curl -k -A Mozilla https://changelog.qgis.org/en/qgis/past-members/json/?years_limit=2 -o ${{ env.FEED_FOLDER }}/qgispastmembers.json
